manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: rygwdn
      url-base: https://github.com/rygwdn
    - name: urob
      url-base: https://github.com/urob
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: main
      import: app/west.yml
      #remote: rygwdn
      #revision: adv360-z3.5-rygwdn
    - name: zmk-tri-state
      remote: urob
      revision: v0.2.1
  self:
    path: config
