manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: refil
      url-base: https://github.com/refil
    - name: rygwdn
      url-base: https://github.com/rygwdn
    - name: dhruvinsh
      url-base: https://github.com/dhruvinsh
    - name: urob
      url-base: https://github.com/urob
  projects:
    - name: zmk
      remote: refil
      revision: adv360-z3.5-2
      import: app/west.yml
      #remote: rygwdn
      #revision: adv360-z3.5-rygwdn
    - name: zmk-tri-state
      #remote: dhruvinsh
      remote: urob
      revision: v0.2.1
  self:
    path: config
