manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: refil
      url-base: https://github.com/refil
    - name: rygwdn
      url-base: https://github.com/rygwdn
  projects:
    - name: zmk
      remote: rygwdn
      revision: adv360-z3.5-rygwdn
      import: app/west.yml
  self:
    path: config
